### ISSUE TITLE
Failure when upgrading to symfony 5.

### ISSUE THREAD

**Issue by NikoGrano** [rips/php-connector-bundle#1]
> post-update-cmd: @auto-scripts
Executing script cache:clear
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /var/.../rips/vendor/rips/connector-bundle/DependencyInjection/Configuration.php on line 20 and at least 1 expected in /.../rips/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
!!  Stack trace:
!!  #0 /.../rips/vendor/rips/connector-bundle/DependencyInjection/Configuration.php(20): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
!!  #1 /.../ripsvendor/symfony/config/Definition/Processor.php(50): RIPS\ConnectorBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
!!  #2 /.../rips/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration()
!!  #3 /.../rips/vendor/rips/connector-b in /.../rips/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by NikoGrano** [comment]
Ref RIPS-538.

**Comment by rips-hb** [comment]
Hello Niko,

we will add support for Symfony 5 with RIPS 3.4 in February.

Best regards,
Hendrik

**Comment by rips-hb** [comment]
Hey Niko,

it is now compatible with Symfony 5.

Cheers,
Hendrik

**Comment by NikoGrano** [comment]
Thanks!
